version: '3.8'

services:
  mysqldb:
#    container_name: tpfoyer_mysql
    image: mysql:5.7
    restart: unless-stopped
    environment: 
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: kaddem_db
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5

  app-kaddem:
#    container_name: kaddem
    image: lawi55/kaddem:0.0.1
    depends_on:
      mysqldb:
        condition: service_healthy
    restart: on-failure
    ports:
      - "8089:8089"
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url" : "jdbc:mysql://mysqldb:3306/kaddem_db?createDatabaseIfNotExist=true",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "",
        "spring.jpa.show-sql": true,
        "spring.jpa.hibernate.ddl-auto": "update",
        "spring.jpa.properties.hibernate.dialect": "org.hibernate.dialect.MySQL57Dialect",
        "server.port": 8089,
        "server.servlet.context-path": "/kaddem",
        "logging.level.org.springframework": "DEBUG",
        "server.tomcat.use-native" : false

      }'
    stdin_open: true
    tty: true

volumes:
  db:
