version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: kaddem
    ports:
      - "3308:3306"  # Expose MySQL on port 3308
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - kaddem-network

  springboot:
    depends_on:
      - mysql
    command: ["./wait-for-it.sh", "mysql:3306", "java", "-jar", "app.jar"]
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/kaddem?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "8089:8089"  # Expose Spring Boot on port 8089
    networks:
      - kaddem-network

networks:
  kaddem-network:

volumes:
  mysql_data:
